name: ETL File Existence Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check required files
        run: |
          # Notebooks
          NOTEBOOKS_DIR="Notebooks"
          for nb in Bronze_Mario.ipynb Silver_Mario.ipynb Gold_Mario.ipynb; do
            if [ ! -f "$NOTEBOOKS_DIR/$nb" ]; then
              echo "❌ $nb missing in $NOTEBOOKS_DIR"
              exit 1
            fi
          done

          # Parquet files (assume they're in 'Parquet Files');
          PARQUET_DIR="Parquet Files"
          parquet_files=(
            bronze.parquet
            silver.parquet
            gold_team_summary.parquet
            gold_player_performance.parquet
            gold_powerup_player.parquet
            gold_world_liveslost.parquet
            gold_top_player_per_team.parquet
            gold_vehicle_counts.parquet
            gold_risk_assessment.parquet
            gold_world_completion.parquet
            gold_hits_team.parquet
            gold_spending_analysis.parquet
          )
          for pq in "${parquet_files[@]}"; do
            if [ ! -f "$PARQUET_DIR/$pq" ]; then
              echo "❌ $pq missing in $PARQUET_DIR"
              exit 1
            fi
          done

          echo "✅ All notebooks and parquet files found!"

